export default {
  netlifyFiles: {
    netlifyToml: {
      build: {
        environment: { FOO: process.env.FOO }
      },
      headers: [
        {
          for: '/*',
          values: { 'X-XSS-Protection': '1; mode=block' }
        }
      ],
      redirects: [
        {
          from: "/api/*",
          to = "https://ngodingbentar-be-v3.vercel.app/api/v1/:splat"
          host = "ngodingbentar-be-v3.vercel.app"
          status = 200
        }
      ]
    }
  }
}