export default {
  netlifyFiles: {
    netlifyToml: {
      redirects: [
        {
          from= "/api/*"
          to= "https://ngodingbentar-be-v3.vercel.app/api/v1/:splat"
          host= "ngodingbentar-be-v3.vercel.app"
          status= 200
        }
      ]
    }
  }
}